apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transcendence-ingress
  annotations:
    # Optionnel : Force HTTPS ou autres middlewares Traefik si besoin
    # traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
    - http:
        paths:
          # Route API -> Gateway
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 42300
          # Route Frontend (Quand il sera prÃªt)
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: frontend
          #       port:
          #         number: 4280
          # Route Kibana (Optionnel, pratique pour le debug)
          - path: /kibana
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 42560