apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  ports:
    - port: 42500 #default port: 5000
      targetPort: 5000
      name: tcp-input
  selector:
    app: logstash
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
      annotations:
        # ======================================================================
        # CONFIGURATION DE L'INJECTION VAULT (Zero Trust)
        # ======================================================================
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "logstash-role"
        
        # Injection des identifiants spécifiques "Writer" pour Logstash
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/infra/logstash"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/infra/logstash" -}}
            export LOGSTASH_USER={{ .Data.data.username | toJSON }}
            export LOGSTASH_PASSWORD={{ .Data.data.password | toJSON }}
          {{- end -}}
    spec:
      serviceAccountName: logstash
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.1
          ports:
            - containerPort: 5000
          env:
            - name: XPACK_MONITORING_ENABLED
              value: "false"
          
          volumeMounts:
            # On monte la ConfigMap qui sera créée par le Makefile
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          
          command: ["/bin/sh", "-c"]
          # On source le fichier config généré par Vault pour charger les variables
          args: [". /vault/secrets/config && /usr/local/bin/docker-entrypoint"]

      volumes:
        - name: config-volume
          configMap:
            # Le nom doit correspondre à celui généré dans le Makefile
            name: logstash-config